after_success:
- bash .travis_after_success.sh
before_install:
- ulimit -c unlimited -S
cache:
  directories:
  - $HOME/.m2
dist: trusty
env:
  global:
  - secure: EAuz7bCKj4r438IEC2y73WVrFwXirflbXA4HhpwVmAFWNqC9LIIpkWcO5GVp773HsZvJBcJjJriP+aKRkImV8AyMgjCeEUv2dlezvbkIIz38vKyw9MWaPIyZ3uS9RCuL7OwGf5BeJ1DvHFYdMBaspZd+EmCYr7abnHdqs+Tm/W8=
  - secure: RI0QcuKMsij3sgRm+Bjhu3X217U6UslvSzcRv13iLLwrTj73zhGi5PF/+kj8Qh1HMQw0oQRR6M8qPqGy82KcjiGbpgPgSy1rVAvkYg+Yw1k7v4l7Vgyj7TNsAM3pqHyojx2jgRjpQsgw/WXQmiahWV6OCOUzdbhEUwVzIXI+vtk=
  - JAVA_OPTS: '''-Xms512m -Xmx2g'''
language: java
matrix:
  include:
  - addons:
      apt:
        packages:
        - oracle-java8-installer
    jdk: oraclejdk8
    os: linux
  - addons:
      apt:
        packages:
        - oracle-java9-installer
    jdk: oraclejdk9
    os: linux
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- ./mvnw test -B
- ./mvnw site -pl docs -B
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
sudo: false
